#### Registrar usuario con pass encriptado.
POST http://localhost:3000/api/users/register
Content-Type: application/json

  {
    
    "nombre": "1",
    "mail": "111s@gmail.com",
    "contraseña":"1234",
    "rol": "admin",
    "ubicacion": "Chile"
  }

### Login usuario
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "mail": "guille@gmail.com",
  "contraseña": "1234"
}

### Obtener todos los usuarios
GET http://localhost:3000/api/users/all

### Obtener el perfil de un usuario

GET http://localhost:3000/api/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTQsIm1haWwiOiJ0aW50eUBnbWFpbC5jb20iLCJyb2wiOiJjb21wcmFkb3IiLCJpYXQiOjE3Mjk3MTYxOTcsImV4cCI6MTcyOTcxOTc5N30.2_yWO5A8Y_KuQOLevCDCOLds_jgyLZUWVecNCQu6Joc

### Actualizar perfil del usuario
PUT http://localhost:3000/api/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzMsIm1haWwiOiJzdUBnbWFpbC5jb20iLCJyb2wiOiJhZG1pbiIsImlhdCI6MTcyODg4MTA2MiwiZXhwIjoxNzI4ODg0NjYyfQ.egbLe-2mub1txgqScs7lPmtbs0ww2Rk5b1mBFVmeG0w
Content-Type: application/json

{
  "nombre": "Juan Actualizado",
  "mail":"Updatemail@gmail.com"
}

### Eliminar usuario
DELETE http://localhost:3000/api/users/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzEsIm1haWwiOiJVcGRhdGVtYWlsQGdtYWlsLmNvbSIsInJvbCI6bnVsbCwiaWF0IjoxNzI4ODgwMzAyLCJleHAiOjE3Mjg4ODM5MDJ9.BotXo1K4v4rTh1AdSc0lSRVV6w_yG9jkjUxQ9d22q88


### Obtener todos los productos
GET http://localhost:3000/api/products/all
Content-Type: application/json

### Crear nuevo producto
POST http://localhost:3000/api/products/newproduct
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzUsIm1haWwiOiJmaW5hbEBnbWFpbC5jb20iLCJyb2wiOiJjb21wcmFkb3IiLCJpYXQiOjE3Mjk0ODU0MTIsImV4cCI6MTcyOTQ4OTAxMn0.sD9C4h_tvTlxy9uYnmM_o-a7Tq5ZIyCoLX2P1ybeSNk
Content-Type: application/json

{
  "titulo": "Disc3 pulento",
  "descripcion": "Descripción del producto",
  "precio": 25000,
  "categoria_id": 2,
  "artista": "Artista Ejemplo",
  "ano": 2023,
  "formato": "Vinilo",
  "condicion": "Nuevo",
  "imagen_url": "estado",
  "estado":"Nuevo"
}

### Actualizar producto existente
PUT http://localhost:3000/api/products/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzEsIm1haWwiOiJVcGRhdGVtYWlsQGdtYWlsLmNvbSIsInJvbCI6bnVsbCwiaWF0IjoxNzI4ODc5NzYyLCJleHAiOjE3Mjg4ODMzNjJ9.ppnsJPxbZTmyenv79wuHNUIADjItR1sULFtiHG9mNrI
Content-Type: application/json

{
  "titulo": "Nuevo título actualizado",
  "descripcion": "Descripción actualizada",
  "precio": 30000,
  "categoria_id": 1,
  "artista": "Nuevo artista",
  "ano": 2021,
  "formato": "Vinilo",
  "condicion": "Nuevo"
}

### Eliminar producto
DELETE http://localhost:3000/api/products/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzEsIm1haWwiOiJVcGRhdGVtYWlsQGdtYWlsLmNvbSIsInJvbCI6bnVsbCwiaWF0IjoxNzI4ODc5NzYyLCJleHAiOjE3Mjg4ODMzNjJ9.ppnsJPxbZTmyenv79wuHNUIADjItR1sULFtiHG9mNrI


### Eliminar usuario autenticado
DELETE http://localhost:3000/api/users/delete/34
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzQsIm1haWwiOiJzdWdhckBnbWFpbC5jb20iLCJyb2wiOiJhZG1pbiIsImlhdCI6MTcyODg4MjA2OCwiZXhwIjoxNzI4ODg1NjY4fQ.6-tW2uUHgFYrPDZ6iI4Bfzc-z0aQM3qLFOD2Qyexe-k


### Obtener todas las compras
GET http://localhost:3000/api/buys/all


### Crear una compra
POST http://localhost:3000/api/buys/newbuy
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsIm1haWwiOiJndWlsbGVAZ21haWwuY29tIiwicm9sIjoiY29tcHJhZG9yIiwiaWF0IjoxNzMwMzA4MTU0LCJleHAiOjE3MzAzMTE3NTR9.PZ2jYt7roQ07NWsFLATJzuwwzd8wDPF6ecv5FcHP22w
Content-Type: application/json

{
  "producto_id": "4",
  "comprador_id": "13",
  "monto_pagado": 25000
}